"""create access records table

Revision ID: 1b4d6a77aa81
Revises: 675b0a6a26e6
Create Date: 2026-07-09 07:21:38.226484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b4d6a77aa81'
down_revision: Union[str, Sequence[str], None] = '675b0a6a26e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_records',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE', 'SLACK', 'GITHUB', name='provider'), nullable=False),
    sa.Column('external_user_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILED', 'REVOKED', name='provisioningstatus'), nullable=False),
    sa.Column('provisioned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_records')
    # ### end Alembic commands ###
