"""add github username to employee

Revision ID: 1f6ed222d471
Revises: bda1deb30daf
Create Date: 2026-07-22 11:55:01.366224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f6ed222d471'
down_revision: Union[str, Sequence[str], None] = 'bda1deb30daf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('github_username', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'employees', ['github_username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'github_username')
    # ### end Alembic commands ###
