"""create audit logs table

Revision ID: bda1deb30daf
Revises: 1b4d6a77aa81
Create Date: 2026-07-10 07:40:39.580820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda1deb30daf'
down_revision: Union[str, Sequence[str], None] = '1b4d6a77aa81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('EMPLOYEE_CREATED', 'ACCOUNT_PROVISIONED', 'ACCOUNT_REVOKED', 'EMPLOYEE_OFFBOARDED', name='auditaction'), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_employee_id'), 'audit_logs', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_employee_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
