from enum import Enum


class EmploymentStatus(str, Enum):
    ACTIVE = "ACTIVE"
    OFFBOARDING = "OFFBOARDING"
    OFFBOARDED = "OFFBOARDED"


class Provider(str, Enum):
    GOOGLE = "GOOGLE"
    SLACK = "SLACK"
    GITHUB = "GITHUB"


class ProvisioningStatus(str, Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    REVOKED = "REVOKED"


class AuditAction(str, Enum):
    EMPLOYEE_CREATED = "EMPLOYEE_CREATED"
    ONBOARDING_STARTED = "ONBOARDING_STARTED"
    PROVISIONING_STARTED = "PROVISIONING_STARTED"
    PROVISIONING_SUCCESS = "PROVISIONING_SUCCESS"
    PROVISIONING_FAILED = "PROVISIONING_FAILED"
    OFFBOARDING_STARTED = "OFFBOARDING_STARTED"
    OFFBOARDING_COMPLETED = "OFFBOARDING_COMPLETED"
    # EMPLOYEE_CREATED = "EMPLOYEE_CREATED"

    ACCOUNT_PROVISIONED = "ACCOUNT_PROVISIONED"

    ACCOUNT_REVOKED = "ACCOUNT_REVOKED"

    EMPLOYEE_OFFBOARDED = "EMPLOYEE_OFFBOARDED"

